marketplace/urls.py
from django.urls import path

from . import views

# The marketplace is the base application, so please visit 127.0.0.1:8000/marketplace
app_name = 'marketplace'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:product_id>/', views.detail, name='detail'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('marketplace/', include('marketplace.urls')),
    path('admin/', admin.site.urls),
]

marketplace/models.py
from django.db import models

# Only one model here: the product. Included the required fields as well as a description field.
class Product(models.Model):
    title = models.CharField(max_length=200)
    price = models.FloatField(default=0)
    inventory_count = models.IntegerField(default=0)
    description = models.CharField(max_length=500, default="Insert Description Here.")

    def __str__(self):
        return self.title

marketplace/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
from django.contrib import messages

# The index view is simply the homepage of the marketplace. There are two context written right away, one to showcase all products,
# and one to showcase all products that have at least 1 inventory. By default, we view all available products. 
def index(request):
    product_list_all = Product.objects.all()
    product_list = Product.objects.exclude(inventory_count = 0)
    # When you click on Show One button, you can view every product including those with 0 inventory through a drop down list.
    if "showOne" in request.POST:
        product = Product.objects.all()[:1].get()
        return render(request, 'marketplace/single.html', {'product':product, 'product_list_all': product_list_all})
    # When you click on Show All button, you can view every available product, redirects you to the homepage.
    if "showAll" in request.POST:
        return render(request, 'marketplace/index.html', {'product_list' : product_list,})
    # Tried to do everything using only 2 views here so I put the View Product button to direct you to the single.html template.
    # This is where you can view each product description individually and click on More Details to go to the purchase page.
    if "showProduct" in request.POST:
        product_id = request.POST["products"]
        product = get_object_or_404(Product, pk = int(product_id))
        return render(request, 'marketplace/single.html', {'product': product, 'product_list_all': product_list_all})
    return render(request, 'marketplace/index.html', {'product_list':product_list,})

def detail(request, product_id):
    product = get_object_or_404(Product, pk = product_id)
    context = {'product': product}
    # If Purchase button is clicked, and there is inventory, it will reduce the inventory count and send the user a message
    # confirming that the product has been purchased. The updated inventory is immediately shown. 
    if "purchase" in request.POST:
        if product.inventory_count >= 1:
            product.inventory_count -= 1
            product.save()
            product_list = Product.objects.exclude(inventory_count = 0)
            messages.info(request, "You have successfully purchased a %s" % product.title)
            return render(request, 'marketplace/detail.html', context)
        else:
            messages.info(request, "%s is sold out!" % product.title)
            return render(request, 'marketplace/detail.html', context)
    return render(request, 'marketplace/detail.html', context)

marketplace/templates/marketplace/detail.html
{% comment %} 
This is the detail page you get directed to when you want to make a purchase.
You can end up here directly through the homepage, or by clicking More Details on a single-view product.
It simply shows the products name, price, inventory, and description.
The user can click on purchase to buy a product, or if it's sold out they will be notified.
{% endcomment %}

<a href="{% url 'marketplace:index' %}"><button >Back</button></a>
<form action="" method="post">
{% csrf_token %}
<br>
{% if product_list_all %}
    <select name="products">
    {% for product in product_list_all %}
        <option value="{{ product.id }}"><a href="{% url 'marketplace:detail' product.id %}">{{ product.title }}</a></option>
    {% endfor %}
    </select>
    <button class="showProduct" name="showProduct" formnovalidate="" type="submit">View Product</button>
{% endif %}

<h1>{{ product.title }}</h1>
<p> ${{product.price}} - {{product.inventory_count}} Left <br> {{ product.description }}<p>
<button class="purchase" name="purchase" formnovalidate="" type="submit">Purchase</button>
</form>
{% if messages %}
    {% for message in messages %}
    <p><strong>
    {% if product.inventory_count == 1 %}{{ message }}, there is {{ product.inventory_count}} left!
    {% elif product.inventory_count == 0 %}{{ message }}
    {% else %}{{ message }}, there are {{ product.inventory_count}} left! {% endif %}
    </p></strong>
    {% endfor %}
{% endif %}

marketplace/templates/marketplace/index.html
{% comment %} 
This is the index page, by default it showcases all available products. Users can choose to view 
each product individually (which then includes even the products with no inventory). This is where
the user is redirected when clicking the back button.
{% endcomment %}

<form action="" method="post">
{% csrf_token %}
<button class="showOne" name="showOne" formnovalidate="" type="submit">Show One</button>
<button class="showAll" name="showAll" formnovalidate="" type="submit">Show All</button>
</form>

{% if product_list %}
    <ul style="list-style: none">
    {% for product in product_list %}
        <li><a href="{% url 'marketplace:detail' product.id %}">{{ product.title }} - {{ product.price }}   
            {% if product.inventory_count <= 10 %} <mark style="color: red;"> ({{product.inventory_count}} left) 
            {% else %} ({{product.inventory_count}} left) {% endif %}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No product in store.</p>
{% endif %}

marketplace/templates/marketplace/single.html
{% comment %} 
This page is where users find themselves when they click Show One button. They will be able to choose
each product in the database using the drop down list and click View Product to see the name and description.
Should they wish to learn more about the product and make a purchase, they can click on More Details which
directs them to the detail page.
{% endcomment %}

<form action="" method="post">
{% csrf_token %}
<button class="showOne" name="showOne" formnovalidate="" type="submit">Show One</button>
<button class="showAll" name="showAll" formnovalidate="" type="submit">Show All</button>
<br><br>
{% if product_list_all %}
    <select name="products">
    {% for product in product_list_all %}
        <option value="{{ product.id }}"><a href="{% url 'marketplace:detail' product.id %}">{{ product.title }}</a></option>
    {% endfor %}
    </select>
    <button class="showProduct" name="showProduct" formnovalidate="" type="submit">View Product</button>
{% else %}
    <p>No product in store.</p>
{% endif %}
</form>

<h1>{{ product.title }}</h1>
<p> {{ product.description }}<p>
<a href="{% url 'marketplace:detail' product.id %}"><button>More Details</button></a>
{% if messages %}
    {% for message in messages %}
    <p><strong>
    {% if product.inventory_count == 1 %}{{ message }}, there is {{ product.inventory_count}} left!
    {% elif product.inventory_count == 0 %}{{ message }}
    {% else %}{{ message }}, there are {{ product.inventory_count}} left! {% endif %}
    </p></strong>
    {% endfor %}
{% endif %}